version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: trademaster
      POSTGRES_USER: eduardo
      POSTGRES_PASSWORD: eduardo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - trademaster-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - trademaster-network

  transactions-app:
    build: .  # Indica que a imagem deve ser construída localmente usando o Dockerfile
    container_name: transactions-app
    depends_on:
      - postgres
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/trademaster
      SPRING_DATASOURCE_USERNAME: eduardo
      SPRING_DATASOURCE_PASSWORD: eduardo
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      BATCH_SIZE: 5
      THREAD_POOL_SIZE: 5
    ports:
      - "8080:8080"
    networks:
      - trademaster-network

volumes:
  postgres_data:

networks:
  trademaster-network:
    driver: bridge